### ISSUE TITLE
Update TNA

### ISSUE THREAD

**Issue by Blayzeing** [ManganLab/insect-eye-simulator#3]
The TNA should be updated to properly reflect examples

**Comment by Blayzeing** [comment]
I will update my TNA so that it properly reflects the experiences I have had

**Comment by Blayzeing** [comment]
Updated, can be found at: https://docs.google.com/document/d/1x__zsIWgP-ROLCvF_x7YNWHrHs-Cm2TVlQdfXJEivF8/edit#

**Comment by michaelmangan** [comment]
Looking good.  Although note that this should be a working document that we constantly refer to ensure your training skills develop as they should.
